import type { Theme } from "../types";

export const bbsDialupTheme: Theme = {
  id: "bbs-dialup",
  name: "BBS Dial-Up",
  author: "Voktty Team",
  description: "1980s bulletin board system with ANSI character cell blocks, ASCII menus and telephone modem telemetry colors",
  skinId: "bbs-dialup",
  windowCorners: "square",
  elevationStyle: "flat",
  pillRadius: "0px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "none",
  density: "compact",
  variations: [
    {
      id: "default",
      name: "BBS 2400 Baud",
      accentColor: "#55ffff",
      variants: {
        dark: {
          colors: {
            background: "#0000aa",
            foreground: "#ffffff",
            primary: "#55ffff",
            accent: "#ffff55",
          },
        },
      },
    },
    {
      id: "telemetry-amber",
      name: "Telemetry Amber",
      accentColor: "#ffb000",
      variants: {
        dark: {
          colors: {
            background: "#160b00",
            foreground: "#ffcc66",
            primary: "#ffb000",
            accent: "#ffd700",
          },
        },
      },
    },
    {
      id: "matrix-dos",
      name: "Matrix DOS",
      accentColor: "#00ff66",
      variants: {
        dark: {
          colors: {
            background: "#001400",
            foreground: "#33ff77",
            primary: "#00ff66",
            accent: "#88ffaa",
          },
        },
      },
    },
  ],
  variants: {
    dark: {
      colors: {
        background: "#0000aa",
        foreground: "#ffffff",
        card: "#000080",
        cardForeground: "#ffffff",
        popover: "#000080",
        popoverForeground: "#ffffff",
        primary: "#55ffff",
        primaryForeground: "#000000",
        secondary: "#000055",
        secondaryForeground: "#ffffff",
        muted: "#000066",
        mutedForeground: "#aaaaaa",
        accent: "#ffff55",
        accentForeground: "#000000",
        destructive: "#ff5555",
        border: "#55ffff",
        input: "#000000",
        ring: "#55ffff",
        sidebar: "#000077",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#55ffff",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ffff55",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#55ffff",
        sidebarRing: "#55ffff",
        radius: "0px",
        surfaceCanvas: "#0000aa",
        surfaceSidebar: "#000077",
        surfaceToolbar: "#000080",
        surfaceCard: "#000080",
        surfacePane: "#0000aa",
        surfaceHeader: "#000080",
        surfacePopover: "#000080",
        surfaceActiveItem: "#55ffff",
        accentAction: "#55ffff",
        accentIndicator: "#ffff55",
        borderSubtle: "#00aaaa",
      },
      terminal: {
        background: "#000000",
        foreground: "#ffffff",
        cursor: "#ffff55",
        cursorAccent: "#000000",
        selection: "#0000aa",
        fontSize: 13,
        ansi: [
          "#000000", "#aa0000", "#00aa00", "#aa5500",
          "#0000aa", "#aa00aa", "#00aaaa", "#aaaaaa",
          "#555555", "#ff5555", "#55ff55", "#ffff55",
          "#5555ff", "#ff55ff", "#55ffff", "#ffffff",
        ],
      },
    },
    light: {
      colors: {
        background: "#000080",
        foreground: "#ffffff",
        card: "#000099",
        cardForeground: "#ffffff",
        popover: "#000099",
        popoverForeground: "#ffffff",
        primary: "#55ffff",
        primaryForeground: "#000000",
        secondary: "#000066",
        secondaryForeground: "#ffffff",
        muted: "#000077",
        mutedForeground: "#aaaaaa",
        accent: "#ffff55",
        accentForeground: "#000000",
        destructive: "#ff5555",
        border: "#55ffff",
        input: "#000033",
        ring: "#55ffff",
        sidebar: "#000070",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#55ffff",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ffff55",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#55ffff",
        sidebarRing: "#55ffff",
        radius: "0px",
        surfaceCanvas: "#000080",
        surfaceSidebar: "#000070",
        surfaceToolbar: "#000099",
        surfaceCard: "#000099",
        surfacePane: "#000080",
        surfaceHeader: "#000099",
        surfacePopover: "#000099",
        surfaceActiveItem: "#55ffff",
        accentAction: "#55ffff",
        accentIndicator: "#ffff55",
        borderSubtle: "#00aaaa",
      },
      terminal: {
        background: "#00001a",
        foreground: "#ffffff",
        cursor: "#ffff55",
        cursorAccent: "#00001a",
        selection: "#0000aa",
        fontSize: 13,
        ansi: [
          "#000000", "#aa0000", "#00aa00", "#aa5500",
          "#0000aa", "#aa00aa", "#00aaaa", "#aaaaaa",
          "#555555", "#ff5555", "#55ff55", "#ffff55",
          "#5555ff", "#ff55ff", "#55ffff", "#ffffff",
        ],
      },
    },
  },
};
