import type { Theme } from "../types";

export const boingWorkbenchTheme: Theme = {
  id: "boing-workbench",
  name: "Boing Workbench",
  author: "Voktty Team",
  description: "Legendary 1985 creative workstation with 4-color sapphire blue, amber topaz, crisp white and obsidian",
  skinId: "boing-workbench",
  windowCorners: "square",
  elevationStyle: "flat",
  pillRadius: "0px",
  borderWidth: "2px",
  borderStyle: "solid",
  focusStyle: "dotted",
  uiFontSmoothing: "none",
  density: "compact",
  variations: [
    {
      id: "default",
      name: "Workbench 1.3",
      accentColor: "#ff8800",
      variants: {
        dark: {
          colors: {
            background: "#0055aa",
            foreground: "#ffffff",
            primary: "#ff8800",
            accent: "#000000",
          },
        },
      },
    },
    {
      id: "wb20",
      name: "Workbench 2.0",
      accentColor: "#5a6b7c",
      variants: {
        dark: {
          colors: {
            background: "#4f5d6b",
            foreground: "#ffffff",
            primary: "#0055aa",
            accent: "#ff8800",
          },
        },
      },
    },
    {
      id: "wb31",
      name: "Workbench 3.1",
      accentColor: "#8e99a4",
      variants: {
        dark: {
          colors: {
            background: "#828c96",
            foreground: "#000000",
            primary: "#0055aa",
            accent: "#ff8800",
          },
        },
      },
    },
  ],
  variants: {
    dark: {
      colors: {
        background: "#0055aa",
        foreground: "#ffffff",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#ff8800",
        primaryForeground: "#000000",
        secondary: "#004488",
        secondaryForeground: "#ffffff",
        muted: "#003b75",
        mutedForeground: "#99c2ee",
        accent: "#ff8800",
        accentForeground: "#000000",
        destructive: "#ff3333",
        border: "#000000",
        input: "#ffffff",
        ring: "#ff8800",
        sidebar: "#004488",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#ff8800",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ff8800",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#000000",
        sidebarRing: "#ff8800",
        radius: "0px",
        surfaceCanvas: "#0055aa",
        surfaceSidebar: "#004488",
        surfaceToolbar: "#ffffff",
        surfaceCard: "#ffffff",
        surfacePane: "#0055aa",
        surfaceHeader: "#ffffff",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#ff8800",
        accentAction: "#ff8800",
        accentIndicator: "#ff8800",
        borderSubtle: "#003366",
      },
      terminal: {
        background: "#0055aa",
        foreground: "#ffffff",
        cursor: "#ff8800",
        cursorAccent: "#0055aa",
        selection: "#ff8800",
        fontSize: 13,
        ansi: [
          "#000000", "#cc2200", "#00aa44", "#ff8800",
          "#0055aa", "#aa00aa", "#00aaaa", "#ffffff",
          "#555555", "#ff4422", "#22cc66", "#ffaa33",
          "#2277cc", "#cc33cc", "#33cccc", "#ffffff",
        ],
      },
    },
    light: {
      colors: {
        background: "#0055aa",
        foreground: "#ffffff",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#ff8800",
        primaryForeground: "#000000",
        secondary: "#004488",
        secondaryForeground: "#ffffff",
        muted: "#003b75",
        mutedForeground: "#99c2ee",
        accent: "#ff8800",
        accentForeground: "#000000",
        destructive: "#ff3333",
        border: "#000000",
        input: "#ffffff",
        ring: "#ff8800",
        sidebar: "#004488",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#ff8800",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ff8800",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#000000",
        sidebarRing: "#ff8800",
        radius: "0px",
        surfaceCanvas: "#0055aa",
        surfaceSidebar: "#004488",
        surfaceToolbar: "#ffffff",
        surfaceCard: "#ffffff",
        surfacePane: "#0055aa",
        surfaceHeader: "#ffffff",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#ff8800",
        accentAction: "#ff8800",
        accentIndicator: "#ff8800",
        borderSubtle: "#003366",
      },
      terminal: {
        background: "#0055aa",
        foreground: "#ffffff",
        cursor: "#ff8800",
        cursorAccent: "#0055aa",
        selection: "#ff8800",
        fontSize: 13,
        ansi: [
          "#000000", "#cc2200", "#00aa44", "#ff8800",
          "#0055aa", "#aa00aa", "#00aaaa", "#ffffff",
          "#555555", "#ff4422", "#22cc66", "#ffaa33",
          "#2277cc", "#cc33cc", "#33cccc", "#ffffff",
        ],
      },
    },
  },
};
