import type { Theme } from "../types";

export const clickWheelPodTheme: Theme = {
  id: "clickwheel-pod",
  name: "ClickWheel Pod",
  author: "Voktty Team",
  description: "Polished stainless steel and pure white porcelain player with cyan selection highlights and compact sans typography",
  skinId: "clickwheel-pod",
  windowCorners: "round",
  elevationStyle: "soft",
  pillRadius: "9999px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "comfortable",
  variations: [
    {
      id: "default",
      name: "White Ceramic & Cyan",
      accentColor: "#007aff",
      variants: {
        light: {
          colors: {
            background: "#f2f4f7",
            foreground: "#111827",
            primary: "#007aff",
            accent: "#0284c7",
          },
        },
      },
    },
    {
      id: "special-black",
      name: "Special Edition Black",
      accentColor: "#dc2626",
      variants: {
        dark: {
          colors: {
            background: "#18181b",
            foreground: "#f4f4f5",
            primary: "#dc2626",
            accent: "#ef4444",
          },
        },
      },
    },
    {
      id: "anodized-silver",
      name: "Anodized Silver",
      accentColor: "#0284c7",
      variants: {
        light: {
          colors: {
            background: "#e5e7eb",
            foreground: "#1f2937",
            primary: "#0284c7",
            accent: "#38bdf8",
          },
        },
      },
    },
  ],
  variants: {
    light: {
      colors: {
        background: "#f2f4f7",
        foreground: "#111827",
        card: "#ffffff",
        cardForeground: "#111827",
        popover: "#ffffff",
        popoverForeground: "#111827",
        primary: "#007aff",
        primaryForeground: "#ffffff",
        secondary: "#e5e7eb",
        secondaryForeground: "#111827",
        muted: "#eef1f5",
        mutedForeground: "#4b5563",
        accent: "#0284c7",
        accentForeground: "#ffffff",
        destructive: "#ef4444",
        border: "#d1d5db",
        input: "#ffffff",
        ring: "#007aff",
        sidebar: "#f9fafb",
        sidebarForeground: "#111827",
        sidebarPrimary: "#007aff",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#0284c7",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#e5e7eb",
        sidebarRing: "#007aff",
        radius: "8px",
        surfaceCanvas: "#f2f4f7",
        surfaceSidebar: "#f9fafb",
        surfaceToolbar: "#ffffff",
        surfaceCard: "#ffffff",
        surfacePane: "#ffffff",
        surfaceHeader: "#f8f9fa",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#007aff",
        accentAction: "#007aff",
        accentIndicator: "#0284c7",
        borderSubtle: "#e5e7eb",
      },
      terminal: {
        background: "#ffffff",
        foreground: "#111827",
        cursor: "#007aff",
        cursorAccent: "#ffffff",
        selection: "#007aff",
        fontSize: 13,
        ansi: [
          "#000000", "#dc2626", "#16a34a", "#ca8a04",
          "#2563eb", "#9333ea", "#0891b2", "#9ca3af",
          "#4b5563", "#ef4444", "#22c55e", "#eab308",
          "#3b82f6", "#a855f7", "#06b6d4", "#111827",
        ],
      },
    },
    dark: {
      colors: {
        background: "#18181b",
        foreground: "#f4f4f5",
        card: "#27272a",
        cardForeground: "#f4f4f5",
        popover: "#27272a",
        popoverForeground: "#f4f4f5",
        primary: "#dc2626",
        primaryForeground: "#ffffff",
        secondary: "#3f3f46",
        secondaryForeground: "#f4f4f5",
        muted: "#27272a",
        mutedForeground: "#a1a1aa",
        accent: "#ef4444",
        accentForeground: "#ffffff",
        destructive: "#ef4444",
        border: "#3f3f46",
        input: "#18181b",
        ring: "#dc2626",
        sidebar: "#202023",
        sidebarForeground: "#f4f4f5",
        sidebarPrimary: "#dc2626",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#ef4444",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#3f3f46",
        sidebarRing: "#dc2626",
        radius: "8px",
        surfaceCanvas: "#18181b",
        surfaceSidebar: "#202023",
        surfaceToolbar: "#27272a",
        surfaceCard: "#27272a",
        surfacePane: "#18181b",
        surfaceHeader: "#27272a",
        surfacePopover: "#27272a",
        surfaceActiveItem: "#dc2626",
        accentAction: "#dc2626",
        accentIndicator: "#ef4444",
        borderSubtle: "#333338",
      },
      terminal: {
        background: "#121214",
        foreground: "#f4f4f5",
        cursor: "#dc2626",
        cursorAccent: "#121214",
        selection: "#dc2626",
        fontSize: 13,
        ansi: [
          "#000000", "#ef4444", "#22c55e", "#eab308",
          "#3b82f6", "#a855f7", "#06b6d4", "#a1a1aa",
          "#71717a", "#f87171", "#4ade80", "#fde047",
          "#60a5fa", "#c084fc", "#22d3ee", "#ffffff",
        ],
      },
    },
  },
};
