import type { Theme } from "../types";

export const commanderBlueTheme: Theme = {
  id: "commander-blue",
  name: "Commander Blue",
  author: "Voktty Team",
  description: "Classic DOS dual-pane file commander with deep navy background, cyan borders and yellow accents",
  skinId: "commander-blue",
  windowCorners: "square",
  elevationStyle: "flat",
  pillRadius: "0px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "dotted",
  uiFontSmoothing: "none",
  density: "compact",
  variations: [
    {
      id: "default",
      name: "Commander Navy",
      accentColor: "#55ffff",
      variants: {
        dark: {
          colors: {
            background: "#000080",
            foreground: "#ffffff",
            primary: "#00aaaa",
            accent: "#ffff55",
          },
        },
      },
    },
    {
      id: "midnight",
      name: "Midnight DOS",
      accentColor: "#00ffaa",
      variants: {
        dark: {
          colors: {
            background: "#080c14",
            foreground: "#ffffff",
            primary: "#00a88f",
            accent: "#55ffff",
          },
        },
      },
    },
    {
      id: "amber",
      name: "Commander Amber",
      accentColor: "#ffaa00",
      variants: {
        dark: {
          colors: {
            background: "#000080",
            foreground: "#ffffff",
            primary: "#ffaa00",
            accent: "#ffff55",
          },
        },
      },
    },
  ],
  variants: {
    dark: {
      colors: {
        background: "#000080",
        foreground: "#ffffff",
        card: "#0000a8",
        cardForeground: "#ffffff",
        popover: "#0000a8",
        popoverForeground: "#ffffff",
        primary: "#00aaaa",
        primaryForeground: "#000000",
        secondary: "#0000a8",
        secondaryForeground: "#ffff55",
        muted: "#000055",
        mutedForeground: "#88bbdd",
        accent: "#ffff55",
        accentForeground: "#000000",
        destructive: "#ff5555",
        border: "#00aaaa",
        input: "#000055",
        ring: "#55ffff",
        sidebar: "#0000a8",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#00aaaa",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ffff55",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#00aaaa",
        sidebarRing: "#55ffff",
        radius: "0px",
        surfaceCanvas: "#000080",
        surfaceSidebar: "#0000a8",
        surfaceToolbar: "#0000a8",
        surfaceCard: "#0000a8",
        surfacePane: "#000080",
        surfaceHeader: "#0000a8",
        surfacePopover: "#0000a8",
        surfaceActiveItem: "#00aaaa",
        accentAction: "#ffff55",
        accentIndicator: "#55ffff",
        borderSubtle: "#0055aa",
      },
      terminal: {
        background: "#000080",
        foreground: "#ffffff",
        cursor: "#00ff00",
        cursorAccent: "#000080",
        selection: "#00aaaa",
        fontSize: 13,
        ansi: [
          "#000000", "#aa0000", "#00aa00", "#aa5500",
          "#0000aa", "#aa00aa", "#00aaaa", "#aaaaaa",
          "#555555", "#ff5555", "#55ff55", "#ffff55",
          "#5555ff", "#ff55ff", "#55ffff", "#ffffff",
        ],
      },
    },
    light: {
      colors: {
        background: "#000080",
        foreground: "#ffffff",
        card: "#0000a8",
        cardForeground: "#ffffff",
        popover: "#0000a8",
        popoverForeground: "#ffffff",
        primary: "#00aaaa",
        primaryForeground: "#000000",
        secondary: "#0000a8",
        secondaryForeground: "#ffff55",
        muted: "#000055",
        mutedForeground: "#88bbdd",
        accent: "#ffff55",
        accentForeground: "#000000",
        destructive: "#ff5555",
        border: "#00aaaa",
        input: "#000055",
        ring: "#55ffff",
        sidebar: "#0000a8",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#00aaaa",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ffff55",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#00aaaa",
        sidebarRing: "#55ffff",
        radius: "0px",
        surfaceCanvas: "#000080",
        surfaceSidebar: "#0000a8",
        surfaceToolbar: "#0000a8",
        surfaceCard: "#0000a8",
        surfacePane: "#000080",
        surfaceHeader: "#0000a8",
        surfacePopover: "#0000a8",
        surfaceActiveItem: "#00aaaa",
        accentAction: "#ffff55",
        accentIndicator: "#55ffff",
        borderSubtle: "#0055aa",
      },
      terminal: {
        background: "#000080",
        foreground: "#ffffff",
        cursor: "#00ff00",
        cursorAccent: "#000080",
        selection: "#00aaaa",
        fontSize: 13,
        ansi: [
          "#000000", "#aa0000", "#00aa00", "#aa5500",
          "#0000aa", "#aa00aa", "#00aaaa", "#aaaaaa",
          "#555555", "#ff5555", "#55ff55", "#ffff55",
          "#5555ff", "#ff55ff", "#55ffff", "#ffffff",
        ],
      },
    },
  },
};
