import type { Theme } from "../types";

export const cubeStepTheme: Theme = {
  id: "cubestep",
  name: "CubeStep",
  author: "Voktty Team",
  description: "Iconic black cube workstation with 3D beveled dark titanium tiles, floating titlebars and high-contrast typography",
  skinId: "cubestep",
  windowCorners: "square",
  elevationStyle: "bevel",
  pillRadius: "0px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "compact",
  variations: [
    {
      id: "default",
      name: "Titanium Black",
      accentColor: "#5078a0",
      variants: {
        dark: {
          colors: {
            background: "#2b2c30",
            foreground: "#ffffff",
            primary: "#5078a0",
            accent: "#7d8694",
          },
        },
      },
    },
    {
      id: "openstep-gray",
      name: "OpenStep Gray",
      accentColor: "#808894",
      variants: {
        dark: {
          colors: {
            background: "#3c3e44",
            foreground: "#ffffff",
            primary: "#808894",
            accent: "#5078a0",
          },
        },
      },
    },
    {
      id: "deep-onyx",
      name: "Deep Onyx",
      accentColor: "#3e6284",
      variants: {
        dark: {
          colors: {
            background: "#1a1b1e",
            foreground: "#ffffff",
            primary: "#3e6284",
            accent: "#525760",
          },
        },
      },
    },
  ],
  variants: {
    dark: {
      colors: {
        background: "#2b2c30",
        foreground: "#ffffff",
        card: "#36383e",
        cardForeground: "#ffffff",
        popover: "#36383e",
        popoverForeground: "#ffffff",
        primary: "#5078a0",
        primaryForeground: "#ffffff",
        secondary: "#1e1f22",
        secondaryForeground: "#e2e6ea",
        muted: "#212226",
        mutedForeground: "#a8b2c0",
        accent: "#7d8694",
        accentForeground: "#ffffff",
        destructive: "#c0392b",
        border: "#151618",
        input: "#1e1f22",
        ring: "#5078a0",
        sidebar: "#222327",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#5078a0",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#7d8694",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#151618",
        sidebarRing: "#5078a0",
        radius: "0px",
        surfaceCanvas: "#2b2c30",
        surfaceSidebar: "#222327",
        surfaceToolbar: "#36383e",
        surfaceCard: "#36383e",
        surfacePane: "#2b2c30",
        surfaceHeader: "#36383e",
        surfacePopover: "#36383e",
        surfaceActiveItem: "#5078a0",
        accentAction: "#5078a0",
        accentIndicator: "#7d8694",
        borderSubtle: "#3e4148",
      },
      terminal: {
        background: "#1e1f22",
        foreground: "#ffffff",
        cursor: "#ffffff",
        cursorAccent: "#1e1f22",
        selection: "#5078a0",
        fontSize: 13,
        ansi: [
          "#000000", "#c0392b", "#27ae60", "#d35400",
          "#2980b9", "#8e44ad", "#16a085", "#bdc3c7",
          "#7f8c8d", "#e74c3c", "#2ecc71", "#f39c12",
          "#3498db", "#9b59b6", "#1abc9c", "#ecf0f1",
        ],
      },
    },
    light: {
      colors: {
        background: "#2b2c30",
        foreground: "#ffffff",
        card: "#36383e",
        cardForeground: "#ffffff",
        popover: "#36383e",
        popoverForeground: "#ffffff",
        primary: "#5078a0",
        primaryForeground: "#ffffff",
        secondary: "#1e1f22",
        secondaryForeground: "#e2e6ea",
        muted: "#212226",
        mutedForeground: "#a8b2c0",
        accent: "#7d8694",
        accentForeground: "#ffffff",
        destructive: "#c0392b",
        border: "#151618",
        input: "#1e1f22",
        ring: "#5078a0",
        sidebar: "#222327",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#5078a0",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#7d8694",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#151618",
        sidebarRing: "#5078a0",
        radius: "0px",
        surfaceCanvas: "#2b2c30",
        surfaceSidebar: "#222327",
        surfaceToolbar: "#36383e",
        surfaceCard: "#36383e",
        surfacePane: "#2b2c30",
        surfaceHeader: "#36383e",
        surfacePopover: "#36383e",
        surfaceActiveItem: "#5078a0",
        accentAction: "#5078a0",
        accentIndicator: "#7d8694",
        borderSubtle: "#3e4148",
      },
      terminal: {
        background: "#1e1f22",
        foreground: "#ffffff",
        cursor: "#ffffff",
        cursorAccent: "#1e1f22",
        selection: "#5078a0",
        fontSize: 13,
        ansi: [
          "#000000", "#c0392b", "#27ae60", "#d35400",
          "#2980b9", "#8e44ad", "#16a085", "#bdc3c7",
          "#7f8c8d", "#e74c3c", "#2ecc71", "#f39c12",
          "#3498db", "#9b59b6", "#1abc9c", "#ecf0f1",
        ],
      },
    },
  },
};
