import type { Theme } from "../types";

export const fluentLight: Theme = {
  id: "fluent-light",
  name: "Fluent Light",
  description: "Clean Windows Fluent Desktop theme with crisp surfaces and high contrast.",
  editorTheme: { dark: "github-dark", light: "github-light" },
  variants: {
    light: {
      colors: {
        background: "#f4f5f8",
        foreground: "#18191c",
        card: "#ffffff",
        cardForeground: "#18191c",
        popover: "#ffffff",
        popoverForeground: "#18191c",
        primary: "#2563eb",
        primaryForeground: "#ffffff",
        secondary: "#f0f1f4",
        secondaryForeground: "#18191c",
        muted: "#f0f1f4",
        mutedForeground: "#6b7280",
        accent: "#e5e7eb",
        accentForeground: "#18191c",
        destructive: "#ef4444",
        border: "rgba(0, 0, 0, 0.08)",
        input: "rgba(0, 0, 0, 0.12)",
        ring: "#2563eb",
        sidebar: "#ebecef",
        sidebarForeground: "#18191c",
        sidebarPrimary: "#2563eb",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#e5e7eb",
        sidebarAccentForeground: "#18191c",
        sidebarBorder: "rgba(0, 0, 0, 0.08)",
        sidebarRing: "#2563eb",
        radius: "0.375rem",
        surfaceCanvas: "#f4f5f8",
        surfaceSidebar: "#ebecef",
        surfaceToolbar: "#f8f9fa",
        surfaceCard: "#ffffff",
        surfacePane: "#ffffff",
        surfaceHeader: "#f0f1f4",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#e5e7eb",
        accentAction: "#2563eb",
        accentIndicator: "#0284c7",
        borderSubtle: "rgba(0, 0, 0, 0.06)",
      },
      terminal: {
        cursor: "#0284c7",
        cursorAccent: "#ffffff",
        selection: "rgba(37, 99, 235, 0.20)",
        ansi: [
          "#18191c", "#b91c1c", "#15803d", "#b45309",
          "#1d4ed8", "#7e22ce", "#0e7490", "#4b5563",
          "#4b5563", "#dc2626", "#16a34a", "#ca8a04",
          "#2563eb", "#9333ea", "#0891b2", "#0f172a",
        ],
      },
    },
  },
};
