import type { Theme } from "../types";

export const humanity2006Theme: Theme = {
  id: "humanity-2006",
  name: "Humanity 2006",
  author: "Voktty Team",
  description: "Warm Human espresso brown and radiant African orange desktop inspired by classic 2006 GNOME 2",
  skinId: "humanity-2006",
  windowCorners: "round",
  elevationStyle: "bevel",
  pillRadius: "3px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "comfortable",
  variations: [
    {
      id: "default",
      name: "Human Espresso",
      accentColor: "#ea6a1a",
      variants: {
        dark: {
          colors: {
            background: "#2b1d19",
            foreground: "#ede6de",
            primary: "#ea6a1a",
            accent: "#f48c36",
          },
        },
      },
    },
    {
      id: "dapper-tan",
      name: "Dapper Tan",
      accentColor: "#dd4814",
      variants: {
        light: {
          colors: {
            background: "#ede6de",
            foreground: "#221815",
            primary: "#dd4814",
            accent: "#3c2b22",
          },
        },
      },
    },
    {
      id: "glider-slate",
      name: "Glider Slate",
      accentColor: "#ea6a1a",
      variants: {
        dark: {
          colors: {
            background: "#2e3436",
            foreground: "#eeeeec",
            primary: "#ea6a1a",
            accent: "#729fcf",
          },
        },
      },
    },
  ],
  variants: {
    dark: {
      colors: {
        background: "#2b1d19",
        foreground: "#ede6de",
        card: "#3c2a23",
        cardForeground: "#ede6de",
        popover: "#3c2a23",
        popoverForeground: "#ede6de",
        primary: "#ea6a1a",
        primaryForeground: "#ffffff",
        secondary: "#402a24",
        secondaryForeground: "#ede6de",
        muted: "#3d2822",
        mutedForeground: "#cbb8af",
        accent: "#f48c36",
        accentForeground: "#ffffff",
        destructive: "#df382c",
        border: "#5c423a",
        input: "#221613",
        ring: "#ea6a1a",
        sidebar: "#241714",
        sidebarForeground: "#ede6de",
        sidebarPrimary: "#ea6a1a",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#f48c36",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#5c423a",
        sidebarRing: "#ea6a1a",
        radius: "3px",
        surfaceCanvas: "#2b1d19",
        surfaceSidebar: "#241714",
        surfaceToolbar: "#3c2a23",
        surfaceCard: "#3c2a23",
        surfacePane: "#2b1d19",
        surfaceHeader: "#3d2c25",
        surfacePopover: "#3c2a23",
        surfaceActiveItem: "#ea6a1a",
        accentAction: "#ea6a1a",
        accentIndicator: "#f48c36",
        borderSubtle: "#422e28",
      },
      terminal: {
        background: "#221613",
        foreground: "#ede6de",
        cursor: "#ea6a1a",
        cursorAccent: "#221613",
        selection: "#ea6a1a",
        fontSize: 13,
        ansi: [
          "#2e3436", "#cc0000", "#4e9a06", "#c4a000",
          "#3465a4", "#75507b", "#06989a", "#d3d7cf",
          "#555753", "#ef2929", "#8ae234", "#fce94f",
          "#729fcf", "#ad7fa8", "#34e2e2", "#eeeeec",
        ],
      },
    },
    light: {
      colors: {
        background: "#ede6de",
        foreground: "#221815",
        card: "#ffffff",
        cardForeground: "#221815",
        popover: "#ffffff",
        popoverForeground: "#221815",
        primary: "#dd4814",
        primaryForeground: "#ffffff",
        secondary: "#dfd6cc",
        secondaryForeground: "#221815",
        muted: "#e2d9cf",
        mutedForeground: "#5c4840",
        accent: "#ea6a1a",
        accentForeground: "#ffffff",
        destructive: "#df382c",
        border: "#c4b5a8",
        input: "#ffffff",
        ring: "#dd4814",
        sidebar: "#e2d9ce",
        sidebarForeground: "#221815",
        sidebarPrimary: "#dd4814",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#ea6a1a",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#c4b5a8",
        sidebarRing: "#dd4814",
        radius: "3px",
        surfaceCanvas: "#ede6de",
        surfaceSidebar: "#e2d9ce",
        surfaceToolbar: "#ffffff",
        surfaceCard: "#ffffff",
        surfacePane: "#ede6de",
        surfaceHeader: "#dd4814",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#dd4814",
        accentAction: "#dd4814",
        accentIndicator: "#ea6a1a",
        borderSubtle: "#dacdc0",
      },
      terminal: {
        background: "#221613",
        foreground: "#ede6de",
        cursor: "#ea6a1a",
        cursorAccent: "#221613",
        selection: "#ea6a1a",
        fontSize: 13,
        ansi: [
          "#2e3436", "#cc0000", "#4e9a06", "#c4a000",
          "#3465a4", "#75507b", "#06989a", "#d3d7cf",
          "#555753", "#ef2929", "#8ae234", "#fce94f",
          "#729fcf", "#ad7fa8", "#34e2e2", "#eeeeec",
        ],
      },
    },
  },
};
