import type { Theme } from "../types";

export const instantChat7Theme: Theme = {
  id: "instant-chat-7",
  name: "Instant Chat 7",
  author: "Voktty Team",
  description: "Mid-2000s instant messenger aesthetic with sky blue headers, tactile bubble cards and online presence accents",
  skinId: "instant-chat-7",
  windowCorners: "round",
  elevationStyle: "soft",
  pillRadius: "8px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "comfortable",
  variations: [
    {
      id: "default",
      name: "Sky Blue Online",
      accentColor: "#0078d7",
      variants: {
        light: {
          colors: {
            background: "#eef5fd",
            foreground: "#0d2847",
            primary: "#0078d7",
            accent: "#28a745",
          },
        },
      },
    },
    {
      id: "sunset-coral",
      name: "Sunset Coral",
      accentColor: "#e85d04",
      variants: {
        light: {
          colors: {
            background: "#fff4ee",
            foreground: "#3a1505",
            primary: "#e85d04",
            accent: "#f48c06",
          },
        },
      },
    },
    {
      id: "violet-night",
      name: "Violet Night",
      accentColor: "#7b2cbf",
      variants: {
        dark: {
          colors: {
            background: "#191124",
            foreground: "#f5effe",
            primary: "#9d4edd",
            accent: "#c77dff",
          },
        },
      },
    },
  ],
  variants: {
    light: {
      colors: {
        background: "#eef5fd",
        foreground: "#0d2847",
        card: "#ffffff",
        cardForeground: "#0d2847",
        popover: "#ffffff",
        popoverForeground: "#0d2847",
        primary: "#0078d7",
        primaryForeground: "#ffffff",
        secondary: "#d6e8fb",
        secondaryForeground: "#0d2847",
        muted: "#dbe7f5",
        mutedForeground: "#46678c",
        accent: "#28a745",
        accentForeground: "#ffffff",
        destructive: "#d9383a",
        border: "#8cb1db",
        input: "#ffffff",
        ring: "#0078d7",
        sidebar: "#e3effc",
        sidebarForeground: "#0d2847",
        sidebarPrimary: "#0078d7",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#28a745",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#8cb1db",
        sidebarRing: "#0078d7",
        radius: "6px",
        surfaceCanvas: "#eef5fd",
        surfaceSidebar: "#e3effc",
        surfaceToolbar: "#ffffff",
        surfaceCard: "#ffffff",
        surfacePane: "#eef5fd",
        surfaceHeader: "#d6e8fb",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#0078d7",
        accentAction: "#0078d7",
        accentIndicator: "#28a745",
        borderSubtle: "#b3cde9",
      },
      terminal: {
        background: "#ffffff",
        foreground: "#0d2847",
        cursor: "#0078d7",
        cursorAccent: "#ffffff",
        selection: "#b8d7f7",
        fontSize: 13,
        ansi: [
          "#0d2847", "#c5221f", "#188038", "#b06000",
          "#1a73e8", "#a142f4", "#12b5cb", "#5f6368",
          "#3c4043", "#d93025", "#1e8e3e", "#e37400",
          "#1967d2", "#9334e6", "#007b83", "#202124",
        ],
      },
    },
    dark: {
      colors: {
        background: "#111d2e",
        foreground: "#e8f1fb",
        card: "#18283e",
        cardForeground: "#e8f1fb",
        popover: "#18283e",
        popoverForeground: "#e8f1fb",
        primary: "#3a9bf5",
        primaryForeground: "#081524",
        secondary: "#223854",
        secondaryForeground: "#e8f1fb",
        muted: "#1d3049",
        mutedForeground: "#8ba7cb",
        accent: "#2ecc71",
        accentForeground: "#081524",
        destructive: "#ff4d4f",
        border: "#2c4669",
        input: "#0d1827",
        ring: "#3a9bf5",
        sidebar: "#0e1826",
        sidebarForeground: "#e8f1fb",
        sidebarPrimary: "#3a9bf5",
        sidebarPrimaryForeground: "#081524",
        sidebarAccent: "#2ecc71",
        sidebarAccentForeground: "#081524",
        sidebarBorder: "#2c4669",
        sidebarRing: "#3a9bf5",
        radius: "6px",
        surfaceCanvas: "#111d2e",
        surfaceSidebar: "#0e1826",
        surfaceToolbar: "#18283e",
        surfaceCard: "#18283e",
        surfacePane: "#111d2e",
        surfaceHeader: "#152438",
        surfacePopover: "#18283e",
        surfaceActiveItem: "#3a9bf5",
        accentAction: "#3a9bf5",
        accentIndicator: "#2ecc71",
        borderSubtle: "#243a57",
      },
      terminal: {
        background: "#0c1522",
        foreground: "#e8f1fb",
        cursor: "#3a9bf5",
        cursorAccent: "#0c1522",
        selection: "#1d406b",
        fontSize: 13,
        ansi: [
          "#0c1522", "#ff4d4f", "#2ecc71", "#f5a623",
          "#3a9bf5", "#b37feb", "#13c2c2", "#8ba7cb",
          "#43638b", "#ff7875", "#52c41a", "#ffc53d",
          "#69c0ff", "#d3adf7", "#36cfc9", "#ffffff",
        ],
      },
    },
  },
};
