import type { Theme } from "../types";

export const kdeTheme: Theme = {
  id: "kde",
  name: "KDE Classic",
  author: "KDE Community / Voktty Team",
  description: "Classic KDE 2/3 desktop with blue gradient titlebar and beveled Qt controls",
  skinId: "kde",
  windowCorners: "round",
  elevationStyle: "bevel",
  pillRadius: "3px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "compact",
  variants: {
    light: {
      colors: {
        background: "#d4dde5",
        foreground: "#1c2b36",
        card: "#ffffff",
        cardForeground: "#1c2b36",
        popover: "#ffffff",
        popoverForeground: "#1c2b36",
        primary: "#0a5f9e",
        primaryForeground: "#ffffff",
        secondary: "#d8e2eb",
        secondaryForeground: "#1c2b36",
        muted: "#e2e8ee",
        mutedForeground: "#2c3e50",
        accent: "#308ecb",
        accentForeground: "#ffffff",
        destructive: "#d94040",
        border: "#90a4b4",
        input: "#ffffff",
        ring: "#0a5f9e",
        sidebar: "#d8e2eb",
        sidebarForeground: "#1c2b36",
        sidebarPrimary: "#0a5f9e",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#308ecb",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#90a4b4",
        sidebarRing: "#0a5f9e",
        radius: "3px",
        surfaceCanvas: "#d4dde5",
        surfaceSidebar: "#d8e2eb",
        surfaceToolbar: "#e2e9f0",
        surfaceCard: "#ffffff",
        surfacePane: "#ffffff",
        surfaceHeader: "#0a5f9e",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#0a5f9e",
        accentAction: "#0a5f9e",
        accentIndicator: "#ffd700",
        borderSubtle: "#b0c0ce",
      },
      terminal: {
        background: "#ffffff",
        foreground: "#000000",
        cursor: "#0a5f9e",
        selection: "#308ecb",
        fontFamily: "'DejaVu Sans Mono', 'Liberation Mono', monospace",
        fontWeight: "normal",
        fontSize: 13,
        ansi: [
          "#000000", "#b21818", "#18b218", "#b26818",
          "#1818b2", "#b218b2", "#18b2b2", "#b2b2b2",
          "#686868", "#ff5454", "#54ff54", "#ffff54",
          "#5454ff", "#ff54ff", "#54ffff", "#ffffff",
        ],
      },
    },
    dark: {
      colors: {
        background: "#1e2227",
        foreground: "#e6edf3",
        card: "#262b32",
        cardForeground: "#e6edf3",
        popover: "#262b32",
        popoverForeground: "#e6edf3",
        primary: "#308ecb",
        primaryForeground: "#ffffff",
        secondary: "#2d343c",
        secondaryForeground: "#e6edf3",
        muted: "#353d47",
        mutedForeground: "#9cb1c5",
        accent: "#0a5f9e",
        accentForeground: "#ffffff",
        destructive: "#e05252",
        border: "#44505d",
        input: "#1e2227",
        ring: "#308ecb",
        sidebar: "#262b32",
        sidebarForeground: "#e6edf3",
        sidebarPrimary: "#308ecb",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#0a5f9e",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#44505d",
        sidebarRing: "#308ecb",
        radius: "3px",
        surfaceCanvas: "#1e2227",
        surfaceSidebar: "#262b32",
        surfaceToolbar: "#2a3038",
        surfaceCard: "#262b32",
        surfacePane: "#1e2227",
        surfaceHeader: "#0a5f9e",
        surfacePopover: "#262b32",
        surfaceActiveItem: "#308ecb",
        accentAction: "#308ecb",
        accentIndicator: "#ffd700",
        borderSubtle: "#3b4550",
      },
      terminal: {
        background: "#1e1e27",
        foreground: "#dcdccc",
        cursor: "#308ecb",
        selection: "#0a5f9e",
        fontFamily: "'DejaVu Sans Mono', 'Liberation Mono', monospace",
        fontWeight: "normal",
        fontSize: 13,
        ansi: [
          "#1e1e27", "#dca3a3", "#72d5a3", "#f0dfaf",
          "#94bff3", "#ec93d3", "#93e0e3", "#dcdccc",
          "#709080", "#dca3a3", "#72d5a3", "#f0dfaf",
          "#94bff3", "#ec93d3", "#93e0e3", "#ffffff",
        ],
      },
    },
  },
};
