import type { Theme } from "../types";

export const mac1Theme: Theme = {
  id: "mac1",
  name: "Macintosh System 1",
  author: "Apple / Voktty Team",
  description: "Authentic 1984 1-bit monochrome GUI with pinstriped titlebar and go-away close box",
  skinId: "mac1",
  windowCorners: "round",
  elevationStyle: "flat",
  pillRadius: "8px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "invert",
  uiFontSmoothing: "none",
  density: "compact",
  variants: {
    light: {
      colors: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#000000",
        primaryForeground: "#ffffff",
        secondary: "#ffffff",
        secondaryForeground: "#000000",
        muted: "#eeeeee",
        mutedForeground: "#111111",
        accent: "#000000",
        accentForeground: "#ffffff",
        destructive: "#000000",
        border: "#000000",
        input: "#ffffff",
        ring: "#000000",
        sidebar: "#ffffff",
        sidebarForeground: "#000000",
        sidebarPrimary: "#000000",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#000000",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#000000",
        sidebarRing: "#000000",
        radius: "4px",
        surfaceCanvas: "#ffffff",
        surfaceSidebar: "#ffffff",
        surfaceToolbar: "#ffffff",
        surfaceCard: "#ffffff",
        surfacePane: "#ffffff",
        surfaceHeader: "#ffffff",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#000000",
        accentAction: "#000000",
        accentIndicator: "#000000",
        borderSubtle: "#000000",
      },
      terminal: {
        background: "#ffffff",
        foreground: "#000000",
        cursor: "#000000",
        selection: "#000000",
        fontFamily: "'Monaco', 'Courier New', monospace",
        fontWeight: "normal",
        fontSize: 13,
        ansi: [
          "#000000", "#000000", "#000000", "#000000",
          "#000000", "#000000", "#000000", "#333333",
          "#333333", "#000000", "#000000", "#000000",
          "#000000", "#000000", "#000000", "#ffffff",
        ],
      },
    },
    dark: {
      colors: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#000000",
        cardForeground: "#ffffff",
        popover: "#000000",
        popoverForeground: "#ffffff",
        primary: "#ffffff",
        primaryForeground: "#000000",
        secondary: "#000000",
        secondaryForeground: "#ffffff",
        muted: "#111111",
        mutedForeground: "#ffffff",
        accent: "#ffffff",
        accentForeground: "#000000",
        destructive: "#ffffff",
        border: "#ffffff",
        input: "#000000",
        ring: "#ffffff",
        sidebar: "#000000",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#ffffff",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#ffffff",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#ffffff",
        sidebarRing: "#ffffff",
        radius: "4px",
        surfaceCanvas: "#000000",
        surfaceSidebar: "#000000",
        surfaceToolbar: "#000000",
        surfaceCard: "#000000",
        surfacePane: "#000000",
        surfaceHeader: "#000000",
        surfacePopover: "#000000",
        surfaceActiveItem: "#ffffff",
        accentAction: "#ffffff",
        accentIndicator: "#ffffff",
        borderSubtle: "#ffffff",
      },
      terminal: {
        background: "#000000",
        foreground: "#ffffff",
        cursor: "#ffffff",
        selection: "#ffffff",
        fontFamily: "'Monaco', 'Courier New', monospace",
        fontWeight: "normal",
        fontSize: 13,
        ansi: [
          "#000000", "#ffffff", "#ffffff", "#ffffff",
          "#ffffff", "#ffffff", "#ffffff", "#cccccc",
          "#666666", "#ffffff", "#ffffff", "#ffffff",
          "#ffffff", "#ffffff", "#ffffff", "#ffffff",
        ],
      },
    },
  },
};
