import type { Theme } from "../types";

export const mediaStation9Theme: Theme = {
  id: "media-station-9",
  name: "Media Station 9",
  author: "Voktty Team",
  description: "Electric cobalt curves, metallic player framing, and neon cyan audio visualizer glow",
  skinId: "media-station-9",
  windowCorners: "round",
  elevationStyle: "soft",
  pillRadius: "9999px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "comfortable",
  variations: [
    {
      id: "default",
      name: "Cobalt Halo",
      accentColor: "#00d2ff",
      variants: {
        dark: {
          colors: {
            background: "#0c192c",
            foreground: "#ffffff",
            primary: "#00d2ff",
            accent: "#00ffcc",
          },
        },
      },
    },
    {
      id: "neon-ruby",
      name: "Neon Ruby",
      accentColor: "#ff2a5f",
      variants: {
        dark: {
          colors: {
            background: "#240b15",
            foreground: "#ffffff",
            primary: "#ff2a5f",
            accent: "#ff7597",
          },
        },
      },
    },
    {
      id: "graphite-silver",
      name: "Graphite Silver",
      accentColor: "#94a3b8",
      variants: {
        dark: {
          colors: {
            background: "#181d24",
            foreground: "#f8fafc",
            primary: "#38bdf8",
            accent: "#94a3b8",
          },
        },
      },
    },
  ],
  variants: {
    dark: {
      colors: {
        background: "#0c192c",
        foreground: "#ffffff",
        card: "#10243e",
        cardForeground: "#ffffff",
        popover: "#10243e",
        popoverForeground: "#ffffff",
        primary: "#00d2ff",
        primaryForeground: "#061526",
        secondary: "#193556",
        secondaryForeground: "#ffffff",
        muted: "#142842",
        mutedForeground: "#8ca6c8",
        accent: "#00ffcc",
        accentForeground: "#061526",
        destructive: "#ff3366",
        border: "#1d406b",
        input: "#081220",
        ring: "#00d2ff",
        sidebar: "#091322",
        sidebarForeground: "#ffffff",
        sidebarPrimary: "#00d2ff",
        sidebarPrimaryForeground: "#061526",
        sidebarAccent: "#00ffcc",
        sidebarAccentForeground: "#061526",
        sidebarBorder: "#1d406b",
        sidebarRing: "#00d2ff",
        radius: "9999px",
        surfaceCanvas: "#0c192c",
        surfaceSidebar: "#091322",
        surfaceToolbar: "#10243e",
        surfaceCard: "#10243e",
        surfacePane: "#0c192c",
        surfaceHeader: "#0d1f35",
        surfacePopover: "#10243e",
        surfaceActiveItem: "#00d2ff",
        accentAction: "#00d2ff",
        accentIndicator: "#00ffcc",
        borderSubtle: "#163152",
      },
      terminal: {
        background: "#070e18",
        foreground: "#e2ecf8",
        cursor: "#00d2ff",
        cursorAccent: "#070e18",
        selection: "#0055aa",
        fontSize: 13,
        ansi: [
          "#070e18", "#ff3366", "#00ffcc", "#ffd000",
          "#00a2ff", "#bf5af2", "#00d2ff", "#8ca6c8",
          "#3a5578", "#ff5c85", "#33ffdd", "#ffe04d",
          "#33b5ff", "#d182f7", "#5ce1ff", "#ffffff",
        ],
      },
    },
    light: {
      colors: {
        background: "#d6e4f0",
        foreground: "#0a192f",
        card: "#edf4fa",
        cardForeground: "#0a192f",
        popover: "#edf4fa",
        popoverForeground: "#0a192f",
        primary: "#0066cc",
        primaryForeground: "#ffffff",
        secondary: "#c0d5e8",
        secondaryForeground: "#0a192f",
        muted: "#b8cee2",
        mutedForeground: "#3b587a",
        accent: "#00a388",
        accentForeground: "#ffffff",
        destructive: "#d91e48",
        border: "#8baecc",
        input: "#ffffff",
        ring: "#0066cc",
        sidebar: "#cbdeed",
        sidebarForeground: "#0a192f",
        sidebarPrimary: "#0066cc",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#00a388",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#8baecc",
        sidebarRing: "#0066cc",
        radius: "9999px",
        surfaceCanvas: "#d6e4f0",
        surfaceSidebar: "#cbdeed",
        surfaceToolbar: "#edf4fa",
        surfaceCard: "#edf4fa",
        surfacePane: "#d6e4f0",
        surfaceHeader: "#c0d5e8",
        surfacePopover: "#edf4fa",
        surfaceActiveItem: "#0066cc",
        accentAction: "#0066cc",
        accentIndicator: "#00a388",
        borderSubtle: "#a3c2dc",
      },
      terminal: {
        background: "#f0f6fb",
        foreground: "#0a192f",
        cursor: "#0066cc",
        cursorAccent: "#f0f6fb",
        selection: "#8baecc",
        fontSize: 13,
        ansi: [
          "#0a192f", "#c01535", "#00875a", "#b7791f",
          "#0066cc", "#7c3aed", "#0284c7", "#64748b",
          "#475569", "#dc2626", "#059669", "#d97706",
          "#2563eb", "#9333ea", "#0891b2", "#0f172a",
        ],
      },
    },
  },
};
