import type { Theme } from "../types";

export const tigerAquaTheme: Theme = {
  id: "tiger-aqua",
  name: "Tiger Aqua",
  author: "Voktty Team",
  description: "2005 brushed aluminum desktop with glossy candy jelly capsule buttons and smooth drop-shadow depth",
  skinId: "tiger-aqua",
  windowCorners: "round",
  elevationStyle: "soft",
  pillRadius: "9999px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "comfortable",
  variations: [
    {
      id: "default",
      name: "Brushed Aluminum Aqua",
      accentColor: "#007aff",
      variants: {
        light: {
          colors: {
            background: "#e8eaed",
            foreground: "#1d1d1f",
            primary: "#007aff",
            accent: "#34c759",
          },
        },
      },
    },
    {
      id: "aqua-graphite",
      name: "Aqua Graphite",
      accentColor: "#6c757d",
      variants: {
        dark: {
          colors: {
            background: "#2e3238",
            foreground: "#f5f6f8",
            primary: "#6c757d",
            accent: "#9ca3af",
          },
        },
      },
    },
    {
      id: "panther-ice",
      name: "Panther Ice",
      accentColor: "#0099ff",
      variants: {
        light: {
          colors: {
            background: "#f0f4f8",
            foreground: "#111827",
            primary: "#0099ff",
            accent: "#00c853",
          },
        },
      },
    },
  ],
  variants: {
    light: {
      colors: {
        background: "#e8eaed",
        foreground: "#1d1d1f",
        card: "#ffffff",
        cardForeground: "#1d1d1f",
        popover: "#ffffff",
        popoverForeground: "#1d1d1f",
        primary: "#007aff",
        primaryForeground: "#ffffff",
        secondary: "#d8dce2",
        secondaryForeground: "#1d1d1f",
        muted: "#dadfe6",
        mutedForeground: "#4b5563",
        accent: "#34c759",
        accentForeground: "#ffffff",
        destructive: "#ff3b30",
        border: "#b0b8c4",
        input: "#ffffff",
        ring: "#007aff",
        sidebar: "#e0e3e8",
        sidebarForeground: "#1d1d1f",
        sidebarPrimary: "#007aff",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#34c759",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#b0b8c4",
        sidebarRing: "#007aff",
        radius: "8px",
        surfaceCanvas: "#e8eaed",
        surfaceSidebar: "#e0e3e8",
        surfaceToolbar: "#ededed",
        surfaceCard: "#ffffff",
        surfacePane: "#ffffff",
        surfaceHeader: "#ededed",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#007aff",
        accentAction: "#007aff",
        accentIndicator: "#34c759",
        borderSubtle: "#d0d6e0",
      },
      terminal: {
        background: "#ffffff",
        foreground: "#1d1d1f",
        cursor: "#007aff",
        cursorAccent: "#ffffff",
        selection: "#007aff",
        fontSize: 13,
        ansi: [
          "#000000", "#c41a16", "#3f6e00", "#aa5d00",
          "#1c00cf", "#832070", "#0077aa", "#8e8e93",
          "#636366", "#e03838", "#4f8c00", "#cf7900",
          "#3454db", "#a33290", "#0099cc", "#1d1d1f",
        ],
      },
    },
    dark: {
      colors: {
        background: "#22252a",
        foreground: "#f4f6f8",
        card: "#2c3037",
        cardForeground: "#f4f6f8",
        popover: "#2c3037",
        popoverForeground: "#f4f6f8",
        primary: "#0a84ff",
        primaryForeground: "#ffffff",
        secondary: "#373c45",
        secondaryForeground: "#f4f6f8",
        muted: "#31353e",
        mutedForeground: "#9ba3af",
        accent: "#30d158",
        accentForeground: "#ffffff",
        destructive: "#ff453a",
        border: "#444b56",
        input: "#1e2126",
        ring: "#0a84ff",
        sidebar: "#25282e",
        sidebarForeground: "#f4f6f8",
        sidebarPrimary: "#0a84ff",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#30d158",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#444b56",
        sidebarRing: "#0a84ff",
        radius: "8px",
        surfaceCanvas: "#22252a",
        surfaceSidebar: "#25282e",
        surfaceToolbar: "#2c3037",
        surfaceCard: "#2c3037",
        surfacePane: "#22252a",
        surfaceHeader: "#2a2d33",
        surfacePopover: "#2c3037",
        surfaceActiveItem: "#0a84ff",
        accentAction: "#0a84ff",
        accentIndicator: "#30d158",
        borderSubtle: "#3a404a",
      },
      terminal: {
        background: "#191b1f",
        foreground: "#f4f6f8",
        cursor: "#0a84ff",
        cursorAccent: "#191b1f",
        selection: "#0a84ff",
        fontSize: 13,
        ansi: [
          "#000000", "#ff453a", "#30d158", "#ffd60a",
          "#0a84ff", "#bf5af2", "#64d2ff", "#aeaeb2",
          "#636366", "#ff6961", "#4cd964", "#ffe620",
          "#409cff", "#da8fff", "#70d7ff", "#ffffff",
        ],
      },
    },
  },
};
