import type { Theme } from "../types";

export const whistlerBlissTheme: Theme = {
  id: "whistler-bliss",
  name: "Whistler Bliss",
  author: "Voktty Team",
  description: "Y2K modern classic desktop with royal blue curved titlebars, emerald start accents and glossy controls",
  skinId: "whistler-bliss",
  windowCorners: "round",
  elevationStyle: "bevel",
  pillRadius: "4px",
  borderWidth: "1px",
  borderStyle: "solid",
  focusStyle: "ring",
  uiFontSmoothing: "antialiased",
  density: "comfortable",
  variations: [
    {
      id: "default",
      name: "Luna Blue",
      accentColor: "#0055ea",
      variants: {
        light: {
          colors: {
            background: "#ece9d8",
            foreground: "#000000",
            primary: "#0055ea",
            accent: "#388e3c",
          },
        },
      },
    },
    {
      id: "homestead-olive",
      name: "Homestead Olive",
      accentColor: "#849a62",
      variants: {
        light: {
          colors: {
            background: "#e5e6d6",
            foreground: "#000000",
            primary: "#637d40",
            accent: "#b27c33",
          },
        },
      },
    },
    {
      id: "metallic-silver",
      name: "Metallic Silver",
      accentColor: "#8c94a6",
      variants: {
        light: {
          colors: {
            background: "#e2e3ea",
            foreground: "#000000",
            primary: "#54657e",
            accent: "#0055ea",
          },
        },
      },
    },
  ],
  variants: {
    light: {
      colors: {
        background: "#ece9d8",
        foreground: "#000000",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#0055ea",
        primaryForeground: "#ffffff",
        secondary: "#d8d4c8",
        secondaryForeground: "#000000",
        muted: "#e2decb",
        mutedForeground: "#2e3642",
        accent: "#388e3c",
        accentForeground: "#ffffff",
        destructive: "#d62010",
        border: "#918b7e",
        input: "#ffffff",
        ring: "#0055ea",
        sidebar: "#d8d4c8",
        sidebarForeground: "#000000",
        sidebarPrimary: "#0055ea",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#388e3c",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#918b7e",
        sidebarRing: "#0055ea",
        radius: "4px",
        surfaceCanvas: "#ece9d8",
        surfaceSidebar: "#d8d4c8",
        surfaceToolbar: "#ece9d8",
        surfaceCard: "#ffffff",
        surfacePane: "#ffffff",
        surfaceHeader: "#0055ea",
        surfacePopover: "#ffffff",
        surfaceActiveItem: "#0055ea",
        accentAction: "#388e3c",
        accentIndicator: "#ff7b00",
        borderSubtle: "#beb8ab",
      },
      terminal: {
        background: "#0c0c0c",
        foreground: "#cccccc",
        cursor: "#ffffff",
        cursorAccent: "#000000",
        selection: "#0055ea",
        fontSize: 13,
        ansi: [
          "#000000", "#c50f1f", "#13a10e", "#c19c00",
          "#0037da", "#881798", "#3a96dd", "#cccccc",
          "#767676", "#e74856", "#16c60c", "#f9f1a5",
          "#3b78ff", "#b4009e", "#61d6d6", "#ffffff",
        ],
      },
    },
    dark: {
      colors: {
        background: "#181e28",
        foreground: "#f0f4fc",
        card: "#202836",
        cardForeground: "#f0f4fc",
        popover: "#202836",
        popoverForeground: "#f0f4fc",
        primary: "#3584e4",
        primaryForeground: "#ffffff",
        secondary: "#2a3648",
        secondaryForeground: "#f0f4fc",
        muted: "#263242",
        mutedForeground: "#8fa2ba",
        accent: "#388e3c",
        accentForeground: "#ffffff",
        destructive: "#e74856",
        border: "#3a4a60",
        input: "#161b24",
        ring: "#3584e4",
        sidebar: "#1c2330",
        sidebarForeground: "#f0f4fc",
        sidebarPrimary: "#3584e4",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#388e3c",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#3a4a60",
        sidebarRing: "#3584e4",
        radius: "4px",
        surfaceCanvas: "#181e28",
        surfaceSidebar: "#1c2330",
        surfaceToolbar: "#202836",
        surfaceCard: "#202836",
        surfacePane: "#181e28",
        surfaceHeader: "#004ecc",
        surfacePopover: "#202836",
        surfaceActiveItem: "#3584e4",
        accentAction: "#388e3c",
        accentIndicator: "#ff7b00",
        borderSubtle: "#2d3a4d",
      },
      terminal: {
        background: "#0c0c0c",
        foreground: "#cccccc",
        cursor: "#ffffff",
        cursorAccent: "#000000",
        selection: "#0055ea",
        fontSize: 13,
        ansi: [
          "#000000", "#c50f1f", "#13a10e", "#c19c00",
          "#0037da", "#881798", "#3a96dd", "#cccccc",
          "#767676", "#e74856", "#16c60c", "#f9f1a5",
          "#3b78ff", "#b4009e", "#61d6d6", "#ffffff",
        ],
      },
    },
  },
};
