/**
 * Maps standard DOM `KeyboardEvent.code` to Windows/PC Scancodes (Set 1) for RDP.
 */
export type ScancodeEntry = {
  scancode: number;
  extended: boolean;
};

const SCANCODE_MAP: Record<string, ScancodeEntry> = {
  Escape: { scancode: 0x01, extended: false },
  Digit1: { scancode: 0x02, extended: false },
  Digit2: { scancode: 0x03, extended: false },
  Digit3: { scancode: 0x04, extended: false },
  Digit4: { scancode: 0x05, extended: false },
  Digit5: { scancode: 0x06, extended: false },
  Digit6: { scancode: 0x07, extended: false },
  Digit7: { scancode: 0x08, extended: false },
  Digit8: { scancode: 0x09, extended: false },
  Digit9: { scancode: 0x0a, extended: false },
  Digit0: { scancode: 0x0b, extended: false },
  Minus: { scancode: 0x0c, extended: false },
  Equal: { scancode: 0x0d, extended: false },
  Backspace: { scancode: 0x0e, extended: false },
  Tab: { scancode: 0x0f, extended: false },
  KeyQ: { scancode: 0x10, extended: false },
  KeyW: { scancode: 0x11, extended: false },
  KeyE: { scancode: 0x12, extended: false },
  KeyR: { scancode: 0x13, extended: false },
  KeyT: { scancode: 0x14, extended: false },
  KeyY: { scancode: 0x15, extended: false },
  KeyU: { scancode: 0x16, extended: false },
  KeyI: { scancode: 0x17, extended: false },
  KeyO: { scancode: 0x18, extended: false },
  KeyP: { scancode: 0x19, extended: false },
  BracketLeft: { scancode: 0x1a, extended: false },
  BracketRight: { scancode: 0x1b, extended: false },
  Enter: { scancode: 0x1c, extended: false },
  ControlLeft: { scancode: 0x1d, extended: false },
  KeyA: { scancode: 0x1e, extended: false },
  KeyS: { scancode: 0x1f, extended: false },
  KeyD: { scancode: 0x20, extended: false },
  KeyF: { scancode: 0x21, extended: false },
  KeyG: { scancode: 0x22, extended: false },
  KeyH: { scancode: 0x23, extended: false },
  KeyJ: { scancode: 0x24, extended: false },
  KeyK: { scancode: 0x25, extended: false },
  KeyL: { scancode: 0x26, extended: false },
  Semicolon: { scancode: 0x27, extended: false },
  Quote: { scancode: 0x28, extended: false },
  Backquote: { scancode: 0x29, extended: false },
  ShiftLeft: { scancode: 0x2a, extended: false },
  Backslash: { scancode: 0x2b, extended: false },
  KeyZ: { scancode: 0x2c, extended: false },
  KeyX: { scancode: 0x2d, extended: false },
  KeyC: { scancode: 0x2e, extended: false },
  KeyV: { scancode: 0x2f, extended: false },
  KeyB: { scancode: 0x30, extended: false },
  KeyN: { scancode: 0x31, extended: false },
  KeyM: { scancode: 0x32, extended: false },
  Comma: { scancode: 0x33, extended: false },
  Period: { scancode: 0x34, extended: false },
  Slash: { scancode: 0x35, extended: false },
  ShiftRight: { scancode: 0x36, extended: false },
  NumpadMultiply: { scancode: 0x37, extended: false },
  AltLeft: { scancode: 0x38, extended: false },
  Space: { scancode: 0x39, extended: false },
  CapsLock: { scancode: 0x3a, extended: false },
  F1: { scancode: 0x3b, extended: false },
  F2: { scancode: 0x3c, extended: false },
  F3: { scancode: 0x3d, extended: false },
  F4: { scancode: 0x3e, extended: false },
  F5: { scancode: 0x3f, extended: false },
  F6: { scancode: 0x40, extended: false },
  F7: { scancode: 0x41, extended: false },
  F8: { scancode: 0x42, extended: false },
  F9: { scancode: 0x43, extended: false },
  F10: { scancode: 0x44, extended: false },
  NumLock: { scancode: 0x45, extended: false },
  ScrollLock: { scancode: 0x46, extended: false },
  Numpad7: { scancode: 0x47, extended: false },
  Numpad8: { scancode: 0x48, extended: false },
  Numpad9: { scancode: 0x49, extended: false },
  NumpadSubtract: { scancode: 0x4a, extended: false },
  Numpad4: { scancode: 0x4b, extended: false },
  Numpad5: { scancode: 0x4c, extended: false },
  Numpad6: { scancode: 0x4d, extended: false },
  NumpadAdd: { scancode: 0x4e, extended: false },
  Numpad1: { scancode: 0x4f, extended: false },
  Numpad2: { scancode: 0x50, extended: false },
  Numpad3: { scancode: 0x51, extended: false },
  Numpad0: { scancode: 0x52, extended: false },
  NumpadDecimal: { scancode: 0x53, extended: false },
  F11: { scancode: 0x57, extended: false },
  F12: { scancode: 0x58, extended: false },

  // Extended keys
  NumpadEnter: { scancode: 0x1c, extended: true },
  ControlRight: { scancode: 0x1d, extended: true },
  NumpadDivide: { scancode: 0x35, extended: true },
  AltRight: { scancode: 0x38, extended: true },
  Home: { scancode: 0x47, extended: true },
  ArrowUp: { scancode: 0x48, extended: true },
  PageUp: { scancode: 0x49, extended: true },
  ArrowLeft: { scancode: 0x4b, extended: true },
  ArrowRight: { scancode: 0x4d, extended: true },
  End: { scancode: 0x4f, extended: true },
  ArrowDown: { scancode: 0x50, extended: true },
  PageDown: { scancode: 0x51, extended: true },
  Insert: { scancode: 0x52, extended: true },
  Delete: { scancode: 0x53, extended: true },
  MetaLeft: { scancode: 0x5b, extended: true },
  MetaRight: { scancode: 0x5c, extended: true },
  ContextMenu: { scancode: 0x5d, extended: true },
};

export function getRdpScancode(code: string): ScancodeEntry | null {
  return SCANCODE_MAP[code] ?? null;
}
