# .github/FUNDING.yml
# Supported funding model platforms

github: [sergewinters, voktty]
# patreon: your_patreon_username
# open_collective: voktty
# ko_fi: sergewinters
# buy_me_a_coffee: sergewinters
# custom: ['https://voktty.dev/sponsor']
