export {
  currentWorkspaceEnv,
  currentWorkspaceScopeKey,
  type DockerWorkspaceConnection,
  documentWorkspaceKey,
  getWslHome,
  isWslWorkspacePath,
  LOCAL_WORKSPACE,
  type NativePtyWorkspaceEnv,
  parseWorkspaceScopeKey,
  persistentWorkspaceEnv,
  type SerialConnectionConfig,
  type SshConnectionConfig,
  type SshWorkspaceConnection,
  useWorkspaceEnvStore,
  type WorkspaceEnv,
  type WslDistro,
  workspaceEnvForNativePty,
  workspaceForDocumentPath,
  workspaceForNativeFs,
  workspaceScopeKey,
} from "./env";
